version: 2
jobs:
  build:
    docker:
      - image: gcc:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command:
            apt update && apt install --yes libgmp-dev libmpfr-dev libmpc-dev zlib1g-dev
      - restore_cache:
          keys:
          - v1-toolchain-{{ checksum "toolchain/Makefile" }}
      - run:
          name: Create cross-compilation toolchain
          command: |
            make toolchain
      - save_cache:
          paths:
            - ./toolchain
          key: v1-toolchain-{{ checksum "toolchain/Makefile" }}
      - run:
          name: Build all
          command: |
            make
